/* التقارير الدورية + الإدارة والإعدادات */
(() => {
'use strict';
const Q = window.Q, {$, $$, esc, ic, L, T} = Q;

/* =============== reports =============== */
Q.views.reports = {perm: 'reports.view', render(parts, q) {
  const m = q.m || Q.ui.repM || Q.ymAdd(Q.ym(Q.now()), -1); Q.ui.repM = m; Q.saveUI();
  const inc = Q.db.all('incidents');
  const inM = inc.filter(x => Q.ym(x.reportedAt) === m);
  const closedM = inc.filter(x => x.closure && Q.ym(x.closure.at) === m);
  const onTime = closedM.length ? Math.round(closedM.filter(x => x.closure.onTime).length / closedM.length * 100) : null;
  const band = {crit: 0, med: 0, low: 0, mute: 0}; inM.forEach(x => band[Q.band(x)]++);
  const sent = inM.filter(Q.isSentinel).length, near = inM.filter(x => x.review && x.review.classification === 'near').length;
  const byDept = Q.db.all('depts').map(d => [d, inM.filter(x => x.deptId === d.id)]).filter(r => r[1].length).sort((a, b) => b[1].length - a[1].length);
  const maxD = Math.max(1, ...byDept.map(r => r[1].length));
  const byType = Q.db.all('types').map(t => [t, inM.filter(x => x.typeId === t.id).length]).filter(r => r[1]).sort((a, b) => b[1] - a[1]).slice(0, 6);
  const prevM = inc.filter(x => Q.ym(x.reportedAt) === Q.ymAdd(m, -1)).length;
  const kp = Q.db.all('kpis').filter(k => k.active !== false);
  const capa = Q.db.all('capa');
  const capaLate = capa.filter(c => Q.capaState(c) === 'late').length, capaDone = capa.filter(c => c.verify && Q.ym(c.verify.at) === m).length;
  const r = Q.readiness();
  const factors = {}; inM.forEach(x => (x.review && x.review.factors || []).forEach(f => factors[f] = (factors[f] || 0) + 1));
  const months = Array.from({length: 12}, (_, i) => Q.ymAdd(Q.ym(Q.now()), i - 11)).filter(x => x <= Q.ym(Q.now()));
  return {title: L('التقارير', 'Reports'), cls: 'report-page', html: `
  <div class="page-head no-print"><div><h2>${L('التقرير الشهري للجودة وسلامة المرضى', 'Monthly quality & patient safety report')}</h2><p>${L('يُعرض على لجنة الجودة ويُطبع أو يُحفظ PDF من المتصفح', 'For the Quality Committee: print or save as PDF')}</p></div>
    <div class="row"><select class="field" data-rep-m aria-label="${L('الشهر', 'Month')}">${months.reverse().map(x => `<option value="${x}" ${x === m ? 'selected' : ''}>${Q.fMonth(x)}</option>`).join('')}</select><button class="btn btn-s" data-act="inc-export">${ic('download')}${L('بيانات البلاغات CSV', 'Reports CSV')}</button><button class="btn btn-p" onclick="window.print()">${ic('print')}${L('طباعة / PDF', 'Print / PDF')}</button></div></div>
  <article class="paper wide">
    <header class="ph"><div><b>${esc(T(Q.S().facility))}</b><small>${L('إدارة الجودة وسلامة المرضى', 'Quality & Patient Safety')}</small></div><div class="pt"><b>${L('التقرير الشهري', 'Monthly report')}</b><small>${Q.fMonth(m)}</small></div><div class="pid">${L('أُعد في', 'Prepared')} ${Q.fDate(Q.now(), false)}</div></header>
    <section><h5>${L('الملخص', 'Summary')}</h5><div class="rep-kpis">
      <div><small>${L('بلاغات مسجلة', 'Reports filed')}</small><b>${inM.length}</b><em class="${inM.length >= prevM ? '' : ''}">${prevM ? `${inM.length >= prevM ? '↑' : '↓'} ${Math.abs(Math.round((inM.length - prevM) / prevM * 100))}% ${L('عن الشهر السابق', 'vs prior')}` : ''}</em></div>
      <div><small>${L('أحداث جسيمة', 'Sentinel events')}</small><b class="${sent ? 'c-crit' : ''}">${sent}</b></div>
      <div><small>${L('أحداث وشيكة', 'Near misses')}</small><b>${near}</b></div>
      <div><small>${L('بلاغات أُغلقت', 'Reports closed')}</small><b>${closedM.length}</b><em>${onTime != null ? L(`${onTime}% ضمن 45 يومًا`, `${onTime}% within 45 days`) : ''}</em></div>
      <div><small>${L('إجراءات مُتحقق منها', 'Actions verified')}</small><b>${capaDone}</b><em>${L(`${capaLate} متأخرة حاليًا`, `${capaLate} currently overdue`)}</em></div>
      <div><small>${L('جاهزية CBAHI', 'CBAHI readiness')}</small><b>${r.pct}%</b></div></div></section>
    <div class="rep-two">
      <section><h5>${L('حسب مستوى الخطورة', 'By risk level')}</h5><table class="ptable"><tbody>
        <tr><td><span class="dot-s crit">${L('عالٍ أو جسيم', 'High / sentinel')}</span></td><td class="num">${band.crit}</td></tr><tr><td><span class="dot-s med">${L('متوسط', 'Moderate')}</span></td><td class="num">${band.med}</td></tr><tr><td><span class="dot-s ok">${L('منخفض', 'Low')}</span></td><td class="num">${band.low}</td></tr><tr><td><span class="dot-s">${L('لم يُقيّم بعد', 'Not rated yet')}</span></td><td class="num">${band.mute}</td></tr></tbody></table></section>
      <section><h5>${L('أكثر أنواع الأحداث', 'Top event types')}</h5><table class="ptable"><tbody>${byType.map(([t, n]) => `<tr><td>${esc(T(t.name))}</td><td class="num">${n}</td></tr>`).join('') || `<tr><td>—</td></tr>`}</tbody></table></section>
    </div>
    <section><h5>${L('حسب القسم', 'By department')}</h5><table class="ptable bars"><tbody>${byDept.map(([d, xs]) => { const c = xs.filter(x => Q.band(x) === 'crit').length; return `<tr><td class="nowrap">${esc(T(d.name))}</td><td style="width:60%"><span class="hbar"><i style="width:${xs.length / maxD * 100}%"></i>${c ? `<i class="c" style="width:${c / maxD * 100}%"></i>` : ''}</span></td><td class="num">${xs.length}</td><td class="num c-crit">${c || ''}</td></tr>`; }).join('') || `<tr><td>${L('لا توجد بلاغات في هذا الشهر.', 'No reports this month.')}</td></tr>`}</tbody></table></section>
    <section><h5>${L('العوامل المساهمة الأكثر تكرارًا', 'Most frequent contributing factors')}</h5><p>${Object.entries(factors).sort((a, b) => b[1] - a[1]).map(([f, n]) => `${T(Q.FACTORS[f])} (${n})`).join(' · ') || '—'}</p></section>
    <section><h5>${L('مؤشرات الأداء', 'Performance indicators')}: ${Q.fMonth(m)}</h5><table class="ptable"><thead><tr><th>${L('المؤشر', 'Indicator')}</th><th>${L('القسم', 'Dept')}</th><th>${L('الهدف', 'Target')}</th><th>${L('القيمة', 'Value')}</th><th>${L('الحالة', 'Status')}</th></tr></thead><tbody>
      ${kp.map(k => { const v = Q.kVal(k, Q.db.get('kpiValues', `${k.id}:${m}`)), s = Q.kState(k, v); return `<tr><td>${esc(T(k.name))}</td><td>${Q.dshort(k.deptId)}</td><td class="ltr">${Q.kTarget(k)}</td><td class="num c-${s}"><b>${Q.kFmt(k, v, false)}</b></td><td>${T(Q.K_ST[s])}</td></tr>`; }).join('')}</tbody></table></section>
    <section><h5>${L('الأحداث الجسيمة والتحقيقات', 'Sentinel events & investigations')}</h5><table class="ptable"><tbody>${Q.db.all('rca').map(rc => { const x = Q.db.get('incidents', rc.incidentId) || {}; return `<tr><td class="ltr">${rc.id}</td><td>${esc(T(x.title))}</td><td>${T(Q.RCA_ST[rc.status])}</td><td>${esc(Q.uname(rc.leadId))}</td></tr>`; }).join('')}</tbody></table></section>
    <section><h5>${L('فجوات الاعتماد الحرجة', 'Critical accreditation gaps')}</h5><ul>${Q.db.all('standards').filter(s => Q.stdState(s) === 'crit').map(s => `<li><b class="ltr">${s.id}</b> ${esc(T(s.name))}: ${L(`${s.elements.filter(e => e.status === 'missing').length} أدلة ناقصة`, `${s.elements.filter(e => e.status === 'missing').length} missing`)}</li>`).join('') || '<li>—</li>'}</ul></section>
    <footer class="pf">${L('منصة سلامة · تقرير مُولد من بيانات المنصة', 'Salamah · generated from platform data')}</footer>
  </article>`, mount: root => $('[data-rep-m]', root).addEventListener('change', e => { Q.ui.repM = e.target.value; Q.saveUI(); Q.render(); })};
}};

/* =============== admin =============== */
Q.views.admin = {perm: 'admin', render(parts) {
  const tab = parts[0] || 'users';
  const tabs = [['users', L('المستخدمون', 'Users')], ['depts', L('الأقسام', 'Departments')], ['types', L('أنواع الأحداث', 'Event types')], ['settings', L('المهل والإعدادات', 'Timelines & settings')], ['data', L('البيانات والنسخ الاحتياطي', 'Data & backup')]];
  let body = '';
  if (tab === 'users') { const us = Q.db.all('users'); body = `<section class="card flush"><div class="card-h"><div><h3>${L(`${us.filter(u => u.active !== false).length} مستخدمًا نشطًا`, `${us.filter(u => u.active !== false).length} active users`)}</h3></div><button class="btn btn-p sm" data-act="u-new">${ic('plus', 'sm')}${L('مستخدم', 'User')}</button></div>
    <div class="tbl-wrap"><table><thead><tr><th>${L('الاسم', 'Name')}</th><th class="hide-m">${L('البريد', 'Email')}</th><th>${L('الدور', 'Role')}</th><th>${L('القسم', 'Dept')}</th><th>${L('الحالة', 'Status')}</th><th></th></tr></thead><tbody>
    ${us.map(u => `<tr><td class="nowrap">${Q.avatar(u.id, 's')} ${esc(T(u.name))}</td><td class="hide-m ltr muted">${esc(u.email)}</td><td>${T(Q.ROLES[u.role])}</td><td>${Q.dshort(u.deptId)}</td><td>${u.active !== false ? `<span class="chip ok">${L('نشط', 'Active')}</span>` : `<span class="chip mute">${L('موقوف', 'Disabled')}</span>`}</td><td><button class="btn-g" data-act="u-edit" data-id="${u.id}">${L('تعديل', 'Edit')}</button></td></tr>`).join('')}</tbody></table></div></section>
    <section class="card" style="margin-top:16px"><div class="card-h"><div><h3>${L('مصفوفة الصلاحيات', 'Permission matrix')}</h3></div></div><div class="card-b tbl-wrap"><table class="perm"><thead><tr><th></th>${Object.keys(Q.ROLES).map(r => `<th>${T(Q.ROLES[r])}</th>`).join('')}</tr></thead><tbody>
    ${[['report.create', L('تقديم بلاغ', 'File a report')], ['incident.supervise', L('تعليق المشرف', 'Supervisor comment')], ['incident.review', L('مراجعة وتحديد SAL', 'Review & SAL')], ['rca.edit', L('إدارة RCA', 'Manage RCA')], ['capa.verify', L('التحقق من CAPA', 'Verify CAPA')], ['kpi.enter', L('إدخال المؤشرات', 'Enter KPIs')], ['cbahi.edit', L('اعتماد أدلة CBAHI', 'Approve CBAHI evidence')], ['device.edit', L('إدارة الأجهزة', 'Manage devices')], ['admin', L('الإدارة', 'Administration')]].map(([p, t]) => `<tr><td>${t}</td>${Object.keys(Q.ROLES).map(r => `<td>${p === 'report.create' || Q.can(p, {role: r}) ? ic('check', 'sm c-ok') : '<span class="muted">—</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`; }
  if (tab === 'depts') body = `<section class="card flush"><div class="card-h"><div><h3>${L('الأقسام', 'Departments')}</h3></div><button class="btn btn-p sm" data-act="d-new">${ic('plus', 'sm')}${L('قسم', 'Department')}</button></div><div class="tbl-wrap"><table><thead><tr><th>${L('القسم', 'Department')}</th><th>${L('الاختصار', 'Short')}</th><th>${L('رئيس القسم', 'Head')}</th><th>${L('المستخدمون', 'Users')}</th><th></th></tr></thead><tbody>
    ${Q.db.all('depts').map(d => `<tr><td>${esc(T(d.name))}</td><td>${esc(T(d.short))}</td><td>${d.headId ? esc(Q.uname(d.headId)) : '—'}</td><td class="num">${Q.db.all('users').filter(u => u.deptId === d.id).length}</td><td><button class="btn-g" data-act="d-edit" data-id="${d.id}">${L('تعديل', 'Edit')}</button></td></tr>`).join('')}</tbody></table></div></section>`;
  if (tab === 'types') body = `<section class="card flush"><div class="card-h"><div><h3>${L('أنواع الأحداث', 'Event types')}</h3><p>${L('تظهر في نموذج البلاغ والتقارير', 'Shown in the report form and reports')}</p></div><button class="btn btn-p sm" data-act="t-new">${ic('plus', 'sm')}${L('نوع', 'Type')}</button></div><div class="tbl-wrap"><table><thead><tr><th>${L('النوع', 'Type')}</th><th>${L('الفئة', 'Category')}</th><th>${L('البلاغات', 'Reports')}</th><th>${L('الحالة', 'Status')}</th><th></th></tr></thead><tbody>
    ${Q.db.all('types').map(t => `<tr><td>${esc(T(t.name))}</td><td>${T(CATS[t.cat] || CATS.other)}</td><td class="num">${Q.db.all('incidents').filter(x => x.typeId === t.id).length}</td><td>${t.active !== false ? `<span class="chip ok">${L('مفعّل', 'Active')}</span>` : `<span class="chip mute">${L('موقوف', 'Hidden')}</span>`}</td><td><button class="btn-g" data-act="t-edit" data-id="${t.id}">${L('تعديل', 'Edit')}</button></td></tr>`).join('')}</tbody></table></div></section>`;
  if (tab === 'settings') { const S = Q.S(); body = `<form class="card" data-settings><div class="card-h"><div><h3>${L('المهل النظامية', 'Regulatory timelines')}</h3><p>${L('تُحسب منها المهل والتنبيهات في كل المنصة', 'Drive every deadline and alert in the platform')}</p></div></div><div class="card-b"><div class="fgrid three">
    ${Q.f.text('supervisorHours', L('تعليق المشرف (ساعة)', 'Supervisor comment (h)'), S.supervisorHours, {type: 'number', req: true, attrs: 'min="1"'})}${Q.f.text('reviewDays', L('مراجعة الجودة (يوم)', 'QPS review (days)'), S.reviewDays, {type: 'number', req: true, attrs: 'min="1"'})}${Q.f.text('externalHours', L('الإخطار الخارجي للحدث الجسيم (ساعة)', 'Sentinel external notice (h)'), S.externalHours, {type: 'number', req: true, attrs: 'min="1"'})}
    ${Q.f.text('rcaMeetingDays', L('اجتماع فريق RCA (يوم)', 'RCA meeting (days)'), S.rcaMeetingDays, {type: 'number', req: true, attrs: 'min="1"'})}${Q.f.text('rcaReportDays', L('رفع تقرير RCA (يوم)', 'RCA report (days)'), S.rcaReportDays, {type: 'number', req: true, attrs: 'min="1"'})}${Q.f.text('closureDays', L('إغلاق البلاغ (يوم)', 'Report closure (days)'), S.closureDays, {type: 'number', req: true, attrs: 'min="1"'})}
    ${Q.f.text('rcaThreshold', L('حد SAL لفتح RCA', 'SAL threshold for RCA'), S.rcaThreshold, {type: 'number', req: true, attrs: 'min="1" max="25"'})}</div></div>
    <div class="card-h" style="border-top:1px solid var(--line-2);padding-top:16px"><div><h3>${L('المنشأة', 'Facility')}</h3></div></div><div class="card-b"><div class="fgrid three">
    ${Q.f.text('facAr', L('اسم المنشأة بالعربية', 'Facility (Arabic)'), S.facility.ar, {req: true})}${Q.f.text('facEn', L('بالإنجليزية', 'English'), S.facility.en, {ltr: true})}${Q.f.text('surveyDate', L('موعد زيارة CBAHI المتوقع', 'Expected CBAHI survey'), S.surveyDate ? Q.toDateInput(S.surveyDate) : '', {type: 'date'})}</div>
    <div class="form-actions"><button class="btn btn-p" type="submit">${L('حفظ الإعدادات', 'Save settings')}</button></div></div></form>`; }
  if (tab === 'data') { const n = Q.COLS.reduce((a, c) => a + Q.db.all(c).length, 0); body = `<section class="card"><div class="card-b data-grid">
    <div><h3>${L('نسخة احتياطية', 'Backup')}</h3><p class="muted">${Q.db.remote ? L(`كل البيانات (${n} سجلًا) محفوظة في قاعدة بيانات SQLite على الخادم ومشتركة بين المستخدمين. نزّل نسخة دورية للاحتفاظ بها.`, `All data (${n} records) is stored in the server's SQLite database and shared by all users. Download a backup regularly.`) : L(`تُحفظ كل البيانات (${n} سجلًا) في هذا المتصفح فقط. نزّل نسخة دورية للاحتفاظ بها أو نقلها لجهاز آخر.`, `All data (${n} records) lives in this browser only. Download a backup regularly.`)}</p><button class="btn btn-p" data-act="db-export">${ic('download')}${L('تنزيل نسخة JSON', 'Download JSON backup')}</button></div>
    <div><h3>${L('استعادة', 'Restore')}</h3><p class="muted">${L('يستبدل البيانات الحالية بمحتوى الملف. المرفقات لا تُضمَّن في النسخة.', 'Replaces current data with the file. Attachments are not included.')}</p><label class="btn btn-s">${ic('clip')}${L('اختيار ملف', 'Choose file')}<input type="file" hidden accept="application/json,.json" data-import></label></div>
    <div><h3>${L('إعادة البيانات التجريبية', 'Reset demo data')}</h3><p class="muted">${L('يحذف كل التعديلات ويعيد المنصة لحالتها الأولى.', 'Deletes all changes and restores the initial demo state.')}</p><button class="btn btn-d" data-act="db-reset">${L('إعادة التعيين', 'Reset')}</button></div>
    <div><h3>${L('حالة التخزين', 'Storage')}</h3><p class="muted">${Q.db.remote ? L('SQLite على الخادم: البيانات مشتركة بين كل المستخدمين والأجهزة.', 'Server SQLite: data shared by all users and devices.') : Q.db.persistent ? L('IndexedDB: البيانات محفوظة بين الجلسات.', 'IndexedDB: data persists between sessions.') : L('الذاكرة المؤقتة فقط: المتصفح يمنع التخزين.', 'Memory only: browser blocks storage.')}</p><p class="muted">${L('أُنشئت البيانات', 'Seeded')} ${Q.fDate(Q.db.data.meta.seededAt)}</p></div></div></section>`; }
  return {title: L('الإعدادات والمستخدمون', 'Settings & users'), mount: root => {
    const sf = $('[data-settings]', root); if (sf) sf.addEventListener('submit', e => { e.preventDefault(); const d = Q.formData(sf), S = Q.S();
      ['supervisorHours', 'reviewDays', 'externalHours', 'rcaMeetingDays', 'rcaReportDays', 'closureDays', 'rcaThreshold'].forEach(k => S[k] = Math.max(1, +d[k] || S[k]));
      S.facility = {ar: d.facAr, en: d.facEn || d.facAr}; S.surveyDate = Q.fromInput(d.surveyDate); Q.db.save('settings'); Q.render(); Q.toast(L('حُفظت الإعدادات', 'Settings saved')); });
    const im = $('[data-import]', root); if (im) im.addEventListener('change', async () => { try { const o = JSON.parse(await im.files[0].text()); if (!await Q.confirm(L('سيتم استبدال كل البيانات الحالية. متابعة؟', 'All current data will be replaced. Continue?'), {danger: true, ok: L('استعادة', 'Restore')})) return; await Q.db.import(o); if (!Q.user(Q.me.id)) Q.logout(); Q.render(); Q.toast(L('استُعيدت البيانات', 'Data restored')); } catch (e) { Q.toast(L('الملف غير صالح.', 'Invalid file.'), 'err'); } });
  }, html: `
  <div class="page-head"><div><h2>${L('الإعدادات والمستخدمون', 'Settings & users')}</h2><p>${esc(T(Q.S().facility))}</p></div></div>
  <div class="tabs" style="margin-bottom:16px">${tabs.map(([k, t]) => `<a href="#/admin/${k}" class="${tab === k ? 'on' : ''}">${t}</a>`).join('')}</div>${body}`};
}};
const CATS = {clinical: ['سريري', 'Clinical'], medication: ['دوائي', 'Medication'], device: ['أجهزة', 'Device'], ipc: ['مكافحة عدوى', 'IPC'], staff: ['سلامة الموظفين', 'Staff safety'], facility: ['مرافق وإمداد', 'Facility & supply'], other: ['أخرى', 'Other']};
Q.settingsSave = () => {};
const uForm = (u = {}) => `<div class="fgrid">${Q.f.text('ar', L('الاسم بالعربية', 'Name (Arabic)'), u.name ? u.name.ar : '', {req: true})}${Q.f.text('en', L('بالإنجليزية', 'English'), u.name ? u.name.en : '', {ltr: true})}${Q.f.text('email', L('البريد الإلكتروني', 'Email'), u.email || '', {req: true, type: 'email', ltr: true})}${Q.f.sel('role', L('الدور', 'Role'), Object.entries(Q.ROLES).map(([k, v]) => [k, T(v)]), u.role || 'reporter')}${Q.f.sel('deptId', L('القسم', 'Department'), Q.deptOpts(), u.deptId || '', {req: true})}${u.id ? Q.f.chk('active', L('حساب نشط', 'Active account'), u.active !== false) : ''}</div>`;
const uFrom = (d, u) => { if (Q.db.all('users').some(x => x.email.toLowerCase() === d.email.toLowerCase() && x.id !== u.id)) throw new Error(L('البريد مستخدم لحساب آخر.', 'Email already in use.')); if (u.id === Q.me.id && (d.active === false || !['admin', 'director'].includes(d.role))) throw new Error(L('لا يمكنك إيقاف حسابك أو إزالة صلاحية الإدارة عنه.', 'You cannot disable yourself or remove your admin role.'));
  return Object.assign(u, {name: {ar: d.ar, en: d.en || d.ar}, email: d.email.trim(), role: d.role, deptId: d.deptId, active: d.active === undefined ? true : !!d.active}); };
Q.act('u-new', () => Q.modal({title: L('مستخدم جديد', 'New user'), wide: true, body: uForm(), sub: L('كلمة المرور التجريبية: demo', 'Pilot password: demo'), onSubmit: d => { const u = uFrom(d, {id: Q.uid('u'), createdAt: Q.iso(Q.now())}); Q.db.put('users', u); Q.render(); Q.toast(L('أُضيف المستخدم', 'User added')); }}));
Q.act('u-edit', el => { const u = Q.user(el.dataset.id); Q.modal({title: L('تعديل المستخدم', 'Edit user'), wide: true, body: uForm(u), onSubmit: d => { uFrom(d, u); Q.db.put('users', u); if (u.id === Q.me.id) Q.me = u; Q.render(); }}); });
const dForm = (d = {}) => `<div class="fgrid">${Q.f.text('ar', L('اسم القسم', 'Name (Arabic)'), d.name ? d.name.ar : '', {req: true})}${Q.f.text('en', L('بالإنجليزية', 'English'), d.name ? d.name.en : '', {ltr: true})}${Q.f.text('sar', L('اسم مختصر', 'Short (Arabic)'), d.short ? d.short.ar : '')}${Q.f.text('sen', L('مختصر بالإنجليزية', 'Short (English)'), d.short ? d.short.en : '', {ltr: true})}${Q.f.sel('headId', L('رئيس القسم', 'Head'), Q.userOpts(u => u.role !== 'reporter'), d.headId || '', {empty: '—', w: true})}</div>`;
const dFrom = (x, d) => Object.assign(d, {name: {ar: x.ar, en: x.en || x.ar}, short: {ar: x.sar || x.ar, en: x.sen || x.en || x.ar}, headId: x.headId || null});
Q.act('d-new', () => Q.modal({title: L('قسم جديد', 'New department'), wide: true, body: dForm(), onSubmit: x => { Q.db.put('depts', dFrom(x, {id: Q.uid('d')})); Q.render(); }}));
Q.act('d-edit', el => { const d = Q.dept(el.dataset.id); Q.modal({title: L('تعديل القسم', 'Edit department'), wide: true, body: dForm(d), onSubmit: x => { dFrom(x, d); Q.db.put('depts', d); Q.render(); }}); });
const tForm = (t = {}) => `<div class="fgrid">${Q.f.text('ar', L('النوع بالعربية', 'Type (Arabic)'), t.name ? t.name.ar : '', {req: true})}${Q.f.text('en', L('بالإنجليزية', 'English'), t.name ? t.name.en : '', {ltr: true})}${Q.f.sel('cat', L('الفئة', 'Category'), Object.entries(CATS).map(([k, v]) => [k, T(v)]), t.cat || 'clinical')}${t.id ? Q.f.chk('active', L('يظهر في نموذج البلاغ', 'Shown in report form'), t.active !== false) : ''}</div>`;
Q.act('t-new', () => Q.modal({title: L('نوع حدث جديد', 'New event type'), body: tForm(), onSubmit: x => { Q.db.put('types', {id: Q.uid('t-'), name: {ar: x.ar, en: x.en || x.ar}, cat: x.cat, active: true}); Q.render(); }}));
Q.act('t-edit', el => { const t = Q.db.get('types', el.dataset.id); Q.modal({title: L('تعديل النوع', 'Edit type'), body: tForm(t), onSubmit: x => { Object.assign(t, {name: {ar: x.ar, en: x.en || x.ar}, cat: x.cat, active: !!x.active}); Q.db.put('types', t); Q.render(); }}); });
Q.act('db-export', () => { Q.download(`salamah-backup-${Q.toDateInput(Q.now())}.json`, JSON.stringify(Q.db.export(), null, 1), 'application/json'); Q.toast(L('نُزّلت النسخة الاحتياطية', 'Backup downloaded')); });
Q.act('db-reset', async () => { if (!await Q.confirm(L('ستُحذف كل البيانات والمرفقات وتعود المنصة لحالتها التجريبية الأولى. لا يمكن التراجع.', 'All data and attachments will be deleted and the demo restored. This cannot be undone.'), {danger: true, ok: L('إعادة التعيين', 'Reset')})) return;
  await Q.db.reset(); Q.pref.del('ui'); Q.ui = {}; Q.logout(); Q.render(); Q.toast(L('أُعيدت البيانات التجريبية', 'Demo data restored')); });
})();
