/* English text for the demo data */
window.SEED_EN = {
"رضيع عمره 9 أيام (2.1 كجم) تلقى جرعة جنتاميسين وريدية تعادل أربعة أضعاف الجرعة الموصوفة. حُضّرت الجرعة من عبوة 40 مجم/مل بدل عبوة 10 مجم/مل المخصصة لحديثي الولادة. اكتُشف الخطأ عند مراجعة الصيدلي السريري للسجل بعد 15 دقيقة.": "A 9-day-old infant (2.1 kg) received an IV gentamicin dose four times the prescribed amount. The dose was drawn from a 40 mg/mL vial instead of the 10 mg/mL neonatal vial. The clinical pharmacist caught the error during record review 15 minutes later.",
"إيقاف أي جرعات لاحقة، سحب مستوى الدواء في الدم، إشعار الطبيب المناوب وطبيب الكلى، وإبلاغ الأسرة وفق سياسة الإفصاح.": "Held further doses, drew a serum level, notified the on-call physician and nephrology, and informed the family under the disclosure policy.",
"حاضنة 4": "Incubator 4",
"رضيع — أسرة المطيري": "Infant — Almutairi family",
"9 أيام": "9 days",
"حدث جسيم. أُبلغ الرئيس التنفيذي هاتفيًا الساعة 18:38. التركيزان مخزنان في الدرج نفسه.": "Sentinel event. CEO informed by phone at 18:38. Both strengths are stored in the same drawer.",
"تشابه العبوات، تحضير أثناء تسليم المناوبة.": "Look-alike vials; preparation during shift handover.",
"فصل التراكيز وإلزام التحقق المزدوج المستقل.": "Separate the strengths and mandate an independent double check.",
"يُفتح تحقيق RCA فورًا. الإخطار الخارجي مستحق خلال 24 ساعة من وقت الحدث.": "RCA to open immediately. External notice due within 24 h of the event.",
"التُقطت عبوة هيبارين 5000 وحدة/مل بدل 1000 وحدة/مل من الرف أثناء تجهيز طلب للتنويم الباطني، واكتُشف الخطأ في التحقق النهائي قبل خروج الطلب.": "A 5,000 units/mL heparin vial was picked instead of 1,000 units/mL while preparing a medical-ward order; caught at final check before release.",
"تصحيح الصرف وإعادة ترتيب الرف مؤقتًا.": "Corrected the dispensing and temporarily rearranged the shelf.",
"صيدلية التنويم": "Inpatient pharmacy",
"مريضة مقبولة في التنويم الباطني بقيت في منطقة الملاحظة 3 ساعات و20 دقيقة بعد قرار التنويم بسبب عدم توفر سرير، دون تدهور في العلامات الحيوية.": "A patient admitted to the medical ward stayed in the observation area for 3 h 20 min after the admission decision because no bed was available; vital signs remained stable.",
"متابعة العلامات الحيوية كل 30 دقيقة وإبلاغ منسق الأسرّة.": "Vital signs every 30 minutes; bed coordinator notified.",
"منطقة الملاحظة": "Observation area",
"أطلق جهاز التنفس في السرير 7 إنذار انخفاض ضغط ثم توقف لمدة 40 ثانية تقريبًا. استُخدم جهاز التنفس اليدوي فورًا ولم تنخفض نسبة الأكسجين عن 91%.": "The bed 7 ventilator raised a low-pressure alarm and stopped for about 40 seconds. Manual bagging started immediately; SpO₂ did not fall below 91%.",
"استبدال الجهاز، عزله بملصق \"خارج الخدمة\"، وإبلاغ الهندسة الطبية الحيوية.": "Replaced the unit, tagged it \"out of service\", and notified biomedical engineering.",
"سرير 7": "Bed 7",
"الجهاز خضع لصيانة وقائية في يونيو. لم يتأذَّ المريض.": "The unit had preventive maintenance in June. The patient was not harmed.",
"عطل محتمل في مستشعر التدفق.": "Probable flow-sensor fault.",
"فحص جميع الأجهزة من الطراز نفسه.": "Inspect all units of the same model.",
"مريضة (71 عامًا) انزلقت أثناء توجهها لدورة المياه دون طلب المساعدة. لا توجد إصابة ظاهرة بعد الفحص.": "A 71-year-old patient slipped while walking to the bathroom unassisted. No visible injury on examination.",
"فحص الطبيب المناوب، إعادة تقييم خطر السقوط (Morse 55)، وتفعيل جرس الاستدعاء بجانب السرير.": "Physician assessment, fall risk re-scored (Morse 55), call bell placed within reach.",
"غرفة 214": "Room 214",
"المريضة مصنفة عالية الخطورة للسقوط لكن لم يُفعّل إنذار السرير.": "The patient is high fall risk but the bed-exit alarm was not activated.",
"عدم تفعيل إنذار مغادرة السرير.": "Bed-exit alarm not activated.",
"تدقيق يومي على مرضى Morse ≥ 45.": "Daily audit of patients with Morse ≥ 45.",
"رُصدت قرحة من الدرجة الثانية في منطقة العجز لمريض منوّم منذ 8 أيام، ولم يُوثّق تغيير الوضعية في آخر مناوبتين.": "A stage 2 sacral pressure injury was found on a patient admitted 8 days ago; repositioning was not documented in the last two shifts.",
"تركيب مرتبة هوائية، جدول تقليب كل ساعتين، واستشارة فريق العناية بالجروح.": "Air mattress fitted, 2-hourly turning chart started, wound care team consulted.",
"سرير 3": "Bed 3",
"نقص في التوثيق خلال المناوبات الليلية.": "Documentation gaps during night shifts.",
"ضغط العمل، غياب تذكير آلي للتقليب.": "Workload; no automatic turning reminder.",
"إضافة تذكير في السجل الإلكتروني.": "Add a reminder in the electronic record.",
"استغرق حضور الطبيب المقيم 27 دقيقة بعد نداء التمريض لمريض بدرجة إنذار مبكر 7.": "The resident took 27 minutes to attend after a nursing call for a patient with an early-warning score of 7.",
"تصعيد مباشر لاستشاري الطوارئ وبدء بروتوكول التدهور السريري.": "Escalated to the ED consultant and started the deterioration protocol.",
"سرير 12": "Bed 12",
"الطبيب المقيم كان في إنعاش حالة أخرى.": "The resident was resuscitating another patient.",
"تغطية غير كافية وقت الذروة.": "Insufficient cover at peak hours.",
"مسار تصعيد مكتوب.": "Written escalation pathway.",
"تأجلت عمليتان مجدولتان 90 دقيقة بسبب نفاد دبابيس التدبيس الجراحي مقاس 60 مم.": "Two scheduled cases were delayed 90 minutes due to a stock-out of 60 mm surgical staple reloads.",
"استعارة كمية من مستشفى الشبكة وإبلاغ إدارة الإمداد.": "Borrowed stock from a network hospital; supply chain notified.",
"غرفة 3": "Theatre 3",
"لا يوجد حد أدنى مُعرّف للمخزون.": "No minimum stock level is defined.",
"غياب تنبيه آلي.": "No automatic alert.",
"تحديد حد أدنى.": "Set a minimum stock level.",
"تعرّض فني مختبر لوخز إبرة أثناء التخلص من أنبوب سحب دم في حاوية ممتلئة فوق الحد.": "A lab technician sustained a needlestick while disposing of a blood-draw set into an overfilled sharps container.",
"غسل الموضع، إحالة لصحة الموظفين، وسحب عينات المصدر وفق البروتوكول.": "Wound washed, referred to employee health, source testing per protocol.",
"غرفة سحب الدم": "Phlebotomy room",
"الحاوية لم تُستبدل في موعدها.": "The container was not replaced on time.",
"جدول الاستبدال غير واضح.": "Replacement schedule unclear.",
"استبدال الحاويات عند ¾.": "Replace containers at ¾ full.",
"أُجريت أشعة مقطعية بالصبغة لمريض يحمل الاسم الأول نفسه لمريض آخر في قائمة الانتظار. لم تظهر مضاعفات للصبغة.": "A contrast CT was performed on a patient sharing a first name with another patient on the waiting list. No contrast reaction occurred.",
"مراقبة المريض ساعتين، إفصاح للمريض، وإجراء الفحص للمريض الصحيح.": "Patient observed for 2 hours, disclosure made, correct patient scanned.",
"النداء بالاسم الأول ممارسة شائعة في القسم.": "Calling patients by first name is common practice in the department.",
"عدم مطابقة المعرّفين.": "Two identifiers not matched.",
"نقطة تحقق قبل الفحص.": "Checkpoint before scanning.",
"صُرف هيدرالازين بدل هيدروكسيزين واكتُشف عند التحقق قبل التسليم.": "Hydralazine was dispensed instead of hydroxyzine and caught at final check.",
"تصحيح الصرف وإبلاغ لجنة الدواء.": "Corrected and reported to the P&T committee.",
"الدواءان متجاوران على الرف.": "The two drugs sit next to each other on the shelf.",
"تخزين متجاور.": "Adjacent storage.",
"شكرًا على الإبلاغ. فُصل تخزين الدواءين وأضيفت ملصقات Tall-Man.": "Thank you for reporting. The two drugs are now stored apart with Tall-Man labels.",
"تورّم بسيط في موضع القسطرة الطرفية لرضيع، أُوقف التسريب مبكرًا.": "Mild swelling at an infant's peripheral cannula site; infusion stopped early.",
"إزالة القسطرة ورفع الطرف ومتابعة الموضع كل ساعة.": "Cannula removed, limb elevated, site checked hourly.",
"اكتُشف مبكرًا.": "Caught early.",
"عدم انتظام فحص الموضع.": "Site checks not done regularly.",
"فحص كل ساعة.": "Hourly checks.",
"اعتُمد بروتوكول الفحص كل ساعة.": "Hourly site-check protocol approved.",
"اتُّخذ الإجراء الفوري المناسب وأُبلغ المشرف.": "Appropriate immediate action taken and supervisor informed.",
"تمت مراجعة الحدث مع الفريق.": "Event reviewed with the team.",
"أُبلغ المبلّغ بنتيجة المراجعة والإجراءات المتخذة.": "Reporter informed of the review outcome and actions taken.",
"وُصف جنتاميسين 5 مجم/كجم (10.5 مجم) كل 36 ساعة.": "Gentamicin 5 mg/kg (10.5 mg) every 36 h prescribed.",
"الصيدلية صرفت الجرعة من مخزون الوحدة دون تحضير مركزي.": "Pharmacy dispensed from ward stock without central preparation.",
"حُضّرت الجرعة من عبوة 40 مجم/مل أثناء تسليم المناوبة.": "Dose drawn from a 40 mg/mL vial during shift handover.",
"أُعطيت الجرعة بعد تحقق شفهي فقط.": "Dose given after a verbal check only.",
"الصيدلي السريري لاحظ عدم تطابق الحجم المسجل.": "Clinical pharmacist noticed a volume mismatch in the record.",
"تسجيل البلاغ وإشعار المشرف والرئيس التنفيذي.": "OVR filed; supervisor and CEO informed.",
"لماذا تلقى الرضيع جرعة أعلى؟": "Why did the infant receive a higher dose?",
"سُحبت الجرعة من تركيز 40 مجم/مل بدل 10 مجم/مل.": "The dose was drawn from 40 mg/mL instead of 10 mg/mL.",
"لماذا كان التركيز الأعلى متاحًا؟": "Why was the higher strength available?",
"يُخزَّن التركيزان في الدرج نفسه وبعبوات متشابهة الشكل.": "Both strengths share a drawer in look-alike vials.",
"لماذا لم يكشفه التحقق المزدوج؟": "Why did the double check miss it?",
"تم التحقق شفهيًا أثناء التسليم دون رؤية العبوة.": "The check was verbal during handover, without seeing the vial.",
"لماذا كان التحقق شفهيًا؟": "Why was the check verbal?",
"المناوبة المسائية كانت بتغطية 61% من الخطة.": "The evening shift ran at 61% of planned staffing.",
"لماذا لم يُعالج نقص التغطية؟": "Why was the staffing gap not addressed?",
"لا توجد قاعدة تصعيد عند انخفاض التغطية عن حد أدنى.": "There is no escalation rule when coverage drops below a minimum.",
"تغطية 61%، تسليم مناوبة متزامن مع التحضير": "61% coverage; handover at the same time as preparation",
"عبوتان متشابهتان بتركيزين مختلفين": "Two look-alike vials of different strengths",
"مقاطعات متكررة أثناء التحضير": "Frequent interruptions during preparation",
"التحقق المزدوج غير مُلزم في السجل الإلكتروني": "Double check not enforced in the electronic record",
"تسليم شفهي غير منظم": "Unstructured verbal handover",
"غياب ضوابط تمنع توفر تراكيز البالغين في وحدة حديثي الولادة، مع ضغط تشغيلي أضعف التحقق المزدوج.": "No control keeps adult strengths out of the NICU, and staffing pressure weakened the double check.",
"فحص روتيني للجهاز دون ملاحظات.": "Routine check, no findings.",
"إنذار انخفاض ضغط متكرر.": "Repeated low-pressure alarm.",
"توقف الجهاز 40 ثانية تقريبًا.": "Unit stopped for about 40 seconds.",
"بدء التنفس اليدوي واستبدال الجهاز.": "Manual bagging started; unit replaced.",
"تسجيل البلاغ وعزل الجهاز.": "OVR filed; unit quarantined.",
"لماذا توقف الجهاز؟": "Why did the unit stop?",
"قراءة خاطئة من مستشعر التدفق أدت لإيقاف وقائي.": "A false flow-sensor reading triggered a safety stop.",
"لماذا أعطى المستشعر قراءة خاطئة؟": "Why was the sensor reading false?",
"رطوبة متراكمة في خط المستشعر.": "Moisture built up in the sensor line.",
"لماذا تراكمت الرطوبة؟": "Why did moisture build up?",
"لم يُستبدل الفلتر وفق جدول الشركة المصنعة.": "The filter was not changed on the manufacturer's schedule.",
"مستشعر التدفق والفلتر": "Flow sensor and filter",
"تحذير المصنع الأخير لم يُعمم على الوحدة": "Latest manufacturer advisory not circulated to the unit",
"جدول استبدال الفلاتر قديم": "Outdated filter change schedule",
"قيد التحقق: فجوة بين جدول استبدال الفلاتر المعتمد في الوحدة وتوصيات الشركة المصنعة.": "Under verification: gap between the unit's filter schedule and the manufacturer's guidance.",
"وصول مريضين بالاسم الأول نفسه لقسم الأشعة.": "Two patients with the same first name arrived at Radiology.",
"نداء المريض بالاسم الأول فقط.": "Patient called by first name only.",
"إجراء الفحص دون مطابقة رقم الملف.": "Scan performed without matching the MRN.",
"اكتشاف الخطأ عند ربط الصور بالطلب.": "Error found when linking images to the order.",
"لماذا أُجري الفحص للمريض الخطأ؟": "Why was the wrong patient scanned?",
"لم يُطابق رقم الملف مع السوار.": "The MRN was not matched to the wristband.",
"لماذا لم تتم المطابقة؟": "Why was it not matched?",
"النداء بالاسم الأول عرف سائد في القسم.": "Calling by first name was routine in the department.",
"لماذا أصبح عرفًا؟": "Why had it become routine?",
"سياسة التعرف لا تحدد نقطة التحقق قبل الفحص.": "The ID policy does not define a checkpoint before scanning.",
"لا توجد نقطة تحقق إلزامية قبل الفحص": "No mandatory checkpoint before scanning",
"النداء بالاسم الأول": "Calling by first name",
"فني جديد في أسبوعه الثاني": "New technologist in his second week",
"ازدحام قائمة الانتظار": "Crowded waiting list",
"سياسة التعرف على المريض لا تُلزم بنقطة تحقق قبل الإجراءات التشخيصية.": "The patient ID policy does not require a checkpoint before diagnostic procedures.",
"اعتماد التحقق من معرّفين (الاسم + رقم الملف) بصوت مسموع قبل كل فحص أشعة": "Require a spoken two-identifier check (name + MRN) before every imaging exam",
"تم تدريب 14 من 20 فنيًا.": "14 of 20 technologists trained.",
"مراجعة توزيع مناوبات الأطباء المقيمين في الطوارئ خلال فترة الذروة": "Review ED resident rota coverage at peak hours",
"تحديث نموذج تسليم المناوبة التمريضية ليشمل الأدوية عالية الخطورة": "Update the nursing handover form to include high-alert medications",
"فحص احترازي لكل أجهزة التنفس من الطراز نفسه (4 أجهزة)": "Precautionary inspection of all same-model ventilators (4 units)",
"تدريب فريق المختبر على التخلص الآمن من الأدوات الحادة واستبدال الحاويات عند ثلاثة أرباعها": "Sharps disposal training for lab staff; replace containers at ¾ full",
"اعتماد مسار تصعيد مكتوب عند درجة إنذار مبكر ≥ 5": "Adopt a written escalation pathway at early-warning score ≥ 5",
"تحديد حد أدنى للمخزون مع تنبيه آلي لمستلزمات غرف العمليات الحرجة": "Set minimum stock levels with automatic alerts for critical OR supplies",
"فصل تخزين تراكيز الجنتاميسين للبالغين عن وحدة حديثي الولادة بالكامل": "Remove adult gentamicin strengths from NICU stock entirely",
"تحقق مزدوج مستقل وموثّق في السجل الإلكتروني للأدوية عالية الخطورة": "Documented independent double check in the eMAR for high-alert drugs",
"قاعدة تصعيد تلقائية عند انخفاض تغطية الكادر عن 75%": "Automatic escalation when staffing coverage drops below 75%",
"فصل تخزين الأدوية متشابهة الأسماء واستخدام ملصقات Tall-Man": "Store look-alike drug names apart and apply Tall-Man labels",
"جولة تدقيق: لا ملاحظات.": "Audit round: no findings.",
"تحديث بروتوكول متابعة موضع القسطرة الطرفية كل ساعة لحديثي الولادة": "Hourly peripheral IV site checks protocol for neonates",
"اعتُمد البروتوكول.": "Protocol approved.",
"مراجعة شهرية لاستهلاك المستلزمات الجراحية مع الإمداد": "Monthly review of surgical supply consumption with supply chain",
"سياسة التصعيد غير معتمدة بعد، ومحضر لجنة الجودة لشهر أغسطس غير مرفق.": "Escalation policy not yet approved; August Quality Committee minutes not attached.",
"التحقيق في OVR-2026-1048 كشف تخزين تركيزين للجنتاميسين في درج واحد.": "The OVR-2026-1048 investigation found two gentamicin strengths in one drawer.",
"جهاز إزالة رجفان في العمليات تجاوز موعد الصيانة الوقائية.": "An OR defibrillator is past its preventive maintenance date.",
"تحديث سجل المخاطر وخطة التوعية الفصلية قيد المراجعة.": "Risk register update and quarterly awareness plan under review.",
"بانتظار نتائج تدقيق الأشعة بعد تطبيق التحقق من معرّفين.": "Awaiting radiology audit results after the two-identifier rollout.",
"نسبة الالتزام 88% في آخر تدقيق؛ الهدف 90%.": "Compliance was 88% at the last audit; target 90%.",
"المؤشرات موثقة ومحدثة ومرفقة بمحاضر المراجعة.": "Indicators are documented, current and linked to review minutes.",
"الخطة معتمدة، ويلزم ربطها بقاعدة التصعيد المقترحة في CAPA-318.": "Plan approved; needs linking to the escalation rule proposed in CAPA-318.",
"كل الأدلة مستوفاة ومراجعة في يوليو.": "All evidence complete and reviewed in July.",
"بانتظار لوحة المستشعر من الوكيل.": "Waiting for the sensor board from the vendor.",
"الشركة الوطنية للتجهيزات الطبية": "National Medical Equipment Co.",
"فحص احترازي — نفس الدفعة التصنيعية.": "Precautionary check — same manufacturing batch.",
"منطقة الإنعاش": "Resus bay",
"فقدان متقطع لإشارة SpO₂.": "Intermittent SpO₂ signal loss.",
"فيليبس السعودية": "Philips Saudi Arabia",
"غرفة 2": "Theatre 2",
"الصيانة الوقائية متأخرة.": "Preventive maintenance overdue.",
"زول الشرق الأوسط": "ZOLL Middle East",
"مكتبة الأدوية محدثة (إصدار 14).": "Drug library current (version 14).",
"بي براون": "B. Braun",
"دريغر": "Dräger",
"محطة التمريض": "Nursing station",
"جي إي للرعاية الصحية": "GE HealthCare",
"غرفة 6": "Theatre 6",
"ميديلا": "Medela",
"الأشعة": "Radiology",
"سيمنز هيلثينيرز": "Siemens Healthineers",
"بنك الدم": "Blood bank",
"هيلمر": "Helmer",
"فحص أولي: خطأ في قراءة مستشعر التدفق. طُلبت لوحة المستشعر من الوكيل.": "Initial check: flow-sensor reading error. Sensor board ordered from the vendor.",
"صيانة وقائية نصف سنوية. اجتاز الاختبارات.": "Semi-annual preventive maintenance. Passed all tests.",
"استبدال كابل SpO₂ لم يحل المشكلة، الجهاز مرسل للوكيل.": "Replacing the SpO₂ cable did not fix it; unit sent to the vendor.",
"اختبار الطاقة والبطارية — ناجح.": "Energy and battery test — passed.",
"تحديث مكتبة الأدوية إلى الإصدار 14.": "Drug library updated to version 14.",
"تم التواصل مع الأسرة صباح اليوم. أرجو تجهيز مسودة الإخطار الخارجي قبل الظهر.": "We spoke with the family this morning. Please prepare the external notice draft before noon.",
"سُحبت عبوات 40 مجم/مل من مخزون الوحدة بالكامل كإجراء مؤقت.": "All 40 mg/mL vials removed from unit stock as an interim measure.",
"الوكيل أكد وجود تحذير فني على دفعة المستشعرات نفسها.": "The vendor confirmed a technical advisory on the same sensor batch.",
"الكادر الفعلي": "Actual staff",
"الكادر حسب الخطة": "Planned staff",
"الأصناف المصروفة": "Items supplied",
"الأصناف المطلوبة": "Items ordered",
"نداءات تأخر ردها > 10 دقائق": "Calls answered after > 10 min",
"إجمالي النداءات": "Total calls",
"حالات الوفاة": "Deaths",
"حالات الخروج": "Discharges",
"حالات العودة": "Returns",
"حوادث السقوط": "Falls",
"أيام التنويم": "Patient days",
"أخطاء دوائية مُبلّغ عنها": "Reported medication errors",
"مجموع أيام الرعاية": "Total care days",
"استدعاء ممرض/طبيب خبير": "Expert nurse/physician calls",
"إجمالي محاولات التركيب": "All cannulation attempts",
"فرص ملتزم بها": "Compliant opportunities",
"فرص مُلاحظة": "Observed opportunities",
"مرضى فُحصوا خلال 30 دقيقة": "Patients seen within 30 min",
"إجمالي مرضى المستوى 3": "All level-3 patients"
};
